blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Discussions"
    url: "https://github.com/anotherhollow1125/hooq/discussions"
    about: "Questions and ideas / è³ªå•ãƒ»ç›¸è«‡ã¯ã“ã¡ã‚‰ã§ã‚‚å¤§ä¸ˆå¤«ã§ã™"
