[my_flavor]
method = """.inspect_err(|_| {
    eprintln!("Error: `{}` @ Line {}: Col: {}", $expr_str_short_oneline, $line, $col);
})
.inspect(|_| {
    println!("Success: `{}` @ Line {}: Col: {}", $expr_str_short_oneline, $line, $col);
})"""
hook_targets = ["?", "return", "tail_expr"]
tail_expr_idents = ["Ok", "Err"]
result_types = ["Result"]
hook_in_macros = true

[my_flavor.ok_or_else]
method = """
.ok_or_else(|| {
    format!("{} [Line: {}, {}]",
        $expr_str_short_oneline,
        $line,
        $nth
    )
})
.$so_far"""
