[book]
authors = ["namnium"]
language = "ja"
src = "src"
title = "hooq Reference 日本語版"

[output.html]
site-url = "/hooq/latest/ja/"
sidebar-header-nav = true

[output.html.playground]
runnable = false
