name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up cargo sort
      run: cargo install cargo-sort --locked --version 2.0.1
    - name: Check Cargo.toml sorted
      run: cargo sort --workspace --check
    - name: Set up nightly cargo fmt
      run: rustup toolchain install nightly-2025-11-18 --component rustfmt
      # nightly のバージョンを変更する際は hooq-macros/tests/special/flavor_not_cargo_project/build_script.rs の TOOLCHAIN も合わせて変更すること
    - name: Check format
      run: cargo +nightly-2025-11-18 fmt --all -- --check
    - name: Check clippy
      run: cargo clippy --all-targets --workspace -- -D warnings
    - name: Set up cargo expand
      run: cargo install cargo-expand --locked --version 1.0.114
    - name: Run tests
      run: cargo test --workspace --no-fail-fast --verbose

  build_and_analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Build
      run: cargo +nightly-2025-11-18 build -Z unstable-options --verbose --timings=html
    - name: Save cargo-timings
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: cargo-timing
        path: target/cargo-timings/cargo-timing.html
        if-no-files-found: warn
