name: Docs and Cargo.toml sync check CI.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sync-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Set up cargo sort
      run: cargo install cargo-sort --locked --version 2.0.1
    - name: Check docs are updated properly
      run: |
        .github/scripts/sync.rs -- --check || \
        .github/scripts/sync.rs -- --check -m publish
